# 1
nombre = "Angel"
apellido = "Alonso"
edad = 19
ciudad = "Aguascalientes"
print("Datos:")
print(f"Nombre: {type(nombre)}")
print(f"Apellido: {type(apellido)}")
print(f"Edad: {type(edad)}")
print(f"ciudad: {type(ciudad)}")
print()
# 2
print("Longitud del nombre:", len(nombre))
# 3. 
print("First name longer than last name:", len(nombre) > len(apellido))
print()
# 4–10
num1 = 5
num2 = 4

suma = num1 + num2
resta = num1 - num2
multiplicacion = num1 * num2
division = num1 / num2
residuo = num2 % num1
exp = num1 ** num2
floor_division = num1 // num2